---
title: "SIF Aldabra tidal predictions"
resource_files:
- data/processed/tide_pred/loc_1/2016.rds
runtime: shiny
output:
  flexdashboard::flex_dashboard:
    navbar:
      - { title: "charts", href: "/aldabratides_chart", align: left}
      - { title: "calendar", align: left }
      - { title: "download", href: "/aldabratides_download", align: left }
    orientation: columns
    css: tides_style.css
    theme: yeti
    vertical_layout: fill
---


```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(magrittr)
library(plotly)
library(ggplot2)
library(RSQLite)
library(DT)

tide_models_params <- readRDS("data/processed/tide_models_params.rds")
source("dashboard_functions.R")
tide <- dplyr::src_sqlite('data/processed/tide_predictions.sqlite3')

# local coordinates of Aldabra
coords <- matrix(c(46.3, -9.4), nrow = 1)


# filter water height for a time interval
read_height <- function(dr, loc){
	d_start <- as.integer(dr[1])
	d_end <- as.integer(dr[2])
	o <- dplyr::tbl(tide, 'tide_prediction') %>%
    dplyr::filter(date >= d_start,
                  date <= d_end, 
    							loc_id == loc) %>%
		dplyr::collect()
	
	o %>%
    dplyr::mutate(time = as.POSIXct(date, tz = "Indian/Mahe", origin = "1970-01-01"))
}


read_high_low <- function(dr, loc) {
	
	d_start <- as.integer(dr[1])
	d_end <- as.integer(dr[2])
	o <- dplyr::tbl(tide, 'tide_high_low') %>%
    dplyr::filter(date >= d_start,
                  date <= d_end, 
    							loc_id == loc) %>%
		dplyr::collect()
	
	o %>%
    dplyr::mutate(time = as.POSIXct(date, tz = "Indian/Mahe", origin = "1970-01-01"))
}
```


Options {.sidebar}
-----------------------------------------------------------------------


```{r inputs_cal}
selectInput("Loc", label = h3("Location"), 
            choices = list("Picard, Research Station" = 1), 
            selected = 1)
y <- dplyr::tbl(tide, 'tide_high_low') %>% 
	dplyr::group_by(year) %>% 
	dplyr::summarise() %>% 
	dplyr::collect()
y <- as.character(y$year) %>% lapply(function(x) x) %>% `names<-`(y$year)
selectInput("Year", label = h4("Year"), 
            choices = y, 
            selected = "2016")

selectInput("Month", label = h4("Month"), 
            choices = list("January" = 1,
                           "February" = 2,
                           "March" = 3, 
                           "April" = 4,
                           "May" = 5,
                           "June" = 6,
                           "July" = 7,
                           "August" = 8,
                           "September" = 9,
                           "October" = 10,
                           "November" = 11,
                           "December" = 12), 
            selected = lubridate::month(Sys.Date()))

```

##### Save the calendar into a PDF:

```{r}

downloadButton('downloadGraph', label = "Download Calendar")

downloadHandler(filename = function() {
  paste0("calendar_", input$Year, "_", input$Month, ".pdf")
}, content = function (file){
  p <- calendar_plot() +
    ggtitle(format(calendar_date(), "%B %Y"))
  ggsave(file, p, width = 11, height = 8.5, units = "in")
})


calendar_date <- reactive({
  if(input$Month == 0) {
    return(0)
  } else {
        as.Date(paste(input$Year, input$Month, "01", sep ="-"), 
                tz = "Indian/Mahe") %>%
      return()
  }
}) # input date


                          
calendar_plot <- reactive({
    l <- as.integer(input$Loc)
  if(calendar_date() == 0) {
    return(empty_plot)
  } else {
   input <- calendar_date()
  
  st <- as.Date(cut(input, "month")) # calculate start of month
  dates31 <- st + 0:30 # st and next 30 dates (31 in all)
  dates <- dates31[months(dates31) == months(st)] # keep only dates in st's month
  
  calendar <- data.frame(date = dates) %>%
    dplyr::mutate(day = as.numeric(format(date, "%d")),
                  week = as.numeric(format(date, "%U")),
                  dow = factor(format(date, "%A"),
                               c("Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"))) 

  d_start <- as.numeric(trunc(as.POSIXct(min(calendar$date)- 7, tz = "Indian/Mahe"), "day"))
  d_end <- as.numeric(trunc(as.POSIXct(max(calendar$date) + 7, tz = "Indian/Mahe"), "day"))
  tides <- read_height(c(d_start, d_end), l)
  
  tides %<>%
    dplyr::mutate(week = as.numeric(format(time, "%U")),
                  dow = factor(format(time, "%A"),
                               c("Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday")),
                  date = time, 
                  time = lubridate::hour(time) + lubridate::minute(time)/60) %>%
    dplyr::slice(1:(nrow(tides)-1)) %>%
    dplyr::filter(week %in% unique(calendar$week)) %>%
    dplyr::mutate(this_month = as.Date(date) %in% calendar$date)
  
  h_l <- read_high_low(c(d_start, d_end), l) %>%
  	dplyr::mutate(week = as.numeric(format(time, "%U")),
                  dow = factor(format(time, "%A"),
                               c("Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday")),
                  date = time, 
                  time = lubridate::hour(time) + lubridate::minute(time)/60,
  								month = lubridate::month(time)) %>%
    dplyr::slice(1:(nrow(tides)-1)) %>%
    dplyr::filter(week %in% unique(calendar$week)) %>%
    dplyr::mutate(this_month = as.Date(date) %in% calendar$date) %>%
    dplyr::mutate(h_l = mapvalues(h_l, c(T, F), c("H", "L")),
                  height = round(height, 1),
                  height = format(height, digits = 1, justify = "right"),
                  high_low = paste(format(date, "%H:%M"), height, h_l, sep = ""),
                  date = as.Date(trunc(date, "day"))) %>%
    dplyr::group_by(date) %>%
    dplyr::summarise(month = mean(month),
                     week = mean(week),
                     dow = unique(dow),
                     this_month = any(this_month),
                     h_l_t = do.call(paste, as.list(c(high_low, sep = "\n")))) 
  
  p <- tides %>%
    dplyr::filter(lubridate::hour(date) >=7,
                  lubridate::hour(date) < 19, 
                  lubridate::minute(date) %% 30 == 0) %>%
    dplyr::mutate(boating = cut(height, c(-10, 1.6, 2, 10))) %>%
    ggplot(aes(x = time, y = height)) +
    geom_rect(fill = "white", xmin = 6, xmax = 20, ymin = -5, ymax = 0, alpha = 0.5) +
    geom_tile(aes(y = 0, fill = boating, alpha = this_month), height = 0.25) +
    geom_line(aes(alpha = this_month), size = 0.7) +
    geom_text(data = calendar, aes(label = day), x = 7, y = -3.25,
              hjust = "left", size =4.5, vjust = "inward",
              family = "Courier") + 
    geom_text(data = dplyr::filter(h_l, T), 
              aes(label = h_l_t, x = 19, y = -3.25, alpha = this_month), 
              vjust = "inward", hjust = "right", size = 3.7,family = "Courier",
              lineheight = 0.8) +
    geom_text(data = data.frame(label = c("8am", "1pm", "6pm"), x =c(8, 13, 18), y = 3),
              aes(x = x, y = y, label = label), hjust = "center", vjust = "inward", size = 2.5, family = "Courier", colour = "grey60") +
    scale_x_continuous(breaks = seq(6,20, 2)) +
    scale_y_continuous(breaks = 0:3, labels = paste(0:3, "m")) +
    facet_grid(week~ dow, scales = "free_x") +
    scale_fill_manual(values = c("#e41a1c", "#ccebc5", "#4daf4a")) +
    scale_alpha_manual(values = c(0.25, 0.75)) +
    theme_bw() + 
    theme(legend.position = "none",
          strip.text.y = element_blank(), 
          axis.text = element_text(family = "Courier", size = 8),
          panel.margin = grid::unit(0, "lines"),
          strip.background = element_rect(fill = "white"), 
          strip.text = element_text(size = 12),
          axis.title = element_text(family= "Courier", size = 10),
          panel.grid.major = element_line(colour = "grey80"))
  
  return(p)
  }
})

```

Column 
-----------------------------------------------------------------------

### 

```{r}
renderPlot({
 calendar_plot()
})
```

> Green and read areas indicate the times at which is safe or not to navigate over the reef crest

