---
title: "SIF Aldabra library catalog"
runtime: shiny
output:
  flexdashboard::flex_dashboard:
    orientation: rows
    css: aldabralibrary.css
    theme: yeti
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(magrittr)
library(xml2)
library(httr)
library(DT)
library(shinyjs)
library(RefManageR)
library(foreach)

fileserver_location <- readLines("./fileserver_location")

if(file.exists("./path_to_db")) {
	db_location <- readLines("./path_to_db")
	path_to_db <- paste0(fileserver_location, db_location)
} else {
	path_to_db <- NULL
}



source('cutter.R')
source('parse_person.R')


find_oclc <- function(author = NULL, 
											title = NULL, 
											isbn = NULL, 
											issn = NULL,
											owi = NULL, 
											summary = 'true'){
	httr::GET('http://classify.oclc.org/classify2/Classify',
						query = list(author = author, 
												 title = title, 
												 isbn = isbn,
												 issn = issn,
												 owi = owi,
												 summary = summary)) %>%
		httr::content()
}

find_xisbn <- function(owi){
	x <- paste0('http://xisbn.worldcat.org/webservices/xid/owi/', owi) %>%
		httr::GET(query = list(method = 'getMetadata',
													 format = 'xml',
													 fl = 'isbn')) %>%
		httr::content() %>% 
		xml_find_first(".//d1:oclcnum") %>%
		xml_attr("isbn")
	if (length(x) == 0) {
		return(NA)
	} else {
		return(stringr::str_split(x, " ")[[1]][1])
	}
}

fields <- c('author', 'format', 'hyr', 'lyr', 'owi', 'title')

full_query_to_df <- function(oo){
	works <- lapply(fields, function(x){
			xml_find_all(oo, ".//d1:work") %>% xml_attr(x) 
		}) %>%
			as.data.frame()
		names(works) <- fields
		works
}

get_cc <- function(x, type = 'lcc'){
	x <- xml_find_all(x, paste0(".//d1:", type)) %>% 
		xml_find_all(".//d1:mostPopular") %>%
		xml_attr("sfa")
	if (length(x) == 0) {
		return(NA)
	} else if (length(x) > 1){
		x[grep("[^a-z]", x, ignore.case = T)][1]
	} else {
		return(x)
	}
}

get_response_code <- function(x){
	xml_find_all(x, ".//d1:response") %>% 
		xml_attr("code") 
}

get_fast  <- function(x, type = 'lcc'){
	x <- xml_find_all(x, paste0(".//d1:", "fast")) %>% 
		xml_find_all(paste0(".//d1:", "heading")) %>%
		xml_text() %>%
		as.list() %>%
		append(c(sep = "; ")) %>%
		do.call(paste, .)
	if (length(x) == 0) {
		return(NA)
	} else {
		return(x)
	}
}

values <- reactiveValues(update_item_table = 0)
```

explore
=======================================================================

Options {.sidebar data-width=300}
-----------------------------------------------------------------------

```{r}
br()
get_record_explore <- reactive({
  validate(
    need(input$explore_table_rows_selected, "Select an item to view details")
  )
  
  items() %>%
    dplyr::slice(input$explore_table_rows_selected)
})

output$book_details_explore <- renderUI({
	if(stringr::str_detect(as.character(get_record_explore()$author), "\\|")){
		pattern <- "^.*?(?=\\|)"
	} else {
		pattern <- ".+"
	}
	list(
	  h4("Title:"),
	  h5(as.character(get_record_explore()$title)),
	  h4("Author:"),
	  h5(stringr::str_extract(as.character(get_record_explore()$author), pattern)),
	  h4("Year:"),
	  h5(as.character(get_record_explore()$year)),
	  h4("Library number:"),
	  h5(as.character(get_record_explore()$number)),
	  h4("ISBN:"),
	  h5(as.character(get_record_explore()$isbn)),
	  h4("Topics:"),
	  h5(as.character(get_record_explore()$fast))
	)
})

uiOutput('book_details_explore')

div(a <- actionButton("deleteEntry", "Delete", width = "100%", onclick = "val=confirm('Are you sure? You cannot undo this action.');
          Shiny.onInputChange('confirm', val);"), class = "buttons-low")

observe(
	toggleState('deleteEntry', condition = !is.null(input$explore_table_rows_selected))
) 

observeEvent(input$deleteEntry,{
  if(input$confirm){
      records <- dplyr::src_sqlite(path_to_db, create = TRUE)
  this_number <- as.character(get_record_explore()$number)
  statement <- paste0("DELETE FROM records WHERE number='",
                      this_number, "'")
  message(statement)
  DBI::dbExecute(records$con, statement)
  values$update_item_table <- values$update_item_table + 1
  }
})

# renderPrint(as.character(get_record_explore()$number))
# renderPrint(input$explore_table_rows_selected)
```

Row
-----------------------------------------------------------------------

###
```{r}
items <- reactive({
  values$update_item_table
	validate(
		need(path_to_db, "The specified location for the database file containing the library records is not valid. Go to advanced > 'Location of the database file' and tell me where I can read an existing database or create a new one.")
	)
	
	records <- dplyr::src_sqlite(path_to_db, create = TRUE)
	
	validate(
		need("records" %in% dplyr::src_tbls(records), "The library has no items. Go ahead and add some :)")
	)

	items <- dplyr::tbl(records, "records") %>%
		dplyr::collect()
	
	DBI::dbDisconnect(records$con)
	items %>% dplyr::arrange(dplyr::desc(date_added))

})

DT::dataTableOutput("explore_table")

output$explore_table <- renderDataTable({
	items() %>%
		dplyr::mutate(library_number = number
		              # date_added = as.POSIXct(date_added)
		              ) %>%
		dplyr::rename(topics = fast) %>%
		dplyr::select(author, 
		              title, 
		              # topics, 
		              # isbn,
		              library_number) %>%
		DT::datatable(style = "bootstrap", 
		              fillContainer = TRUE, 
		              selection = 'single', 
									options = list(dom ="ftip"))	
})
```


add items
=======================================================================

Options {.sidebar data-width=300}
-----------------------------------------------------------------------

```{r}
library(shinyjs)

useShinyjs(rmd = TRUE)

textInput('inTitle', 'Title', value = NULL)
textInput('inAuthor', 'Author', value = NULL)
selectInput("inYear", "Year", c("Choose one" = '', 1800:lubridate::year(Sys.Date())),
						selected = NULL)
# textInput('inEdition', 'Year of first edition', value = NULL)
textInput('inISBN', 'ISBN', value = NULL)
# textInput('inISSN', 'ISSN', value = NULL)
textInput('inLCC', 'Library of Congress Classification Number', value = NULL)

actionButton('search', 'Search', width = '50%')
actionButton('clear', 'Clear form', width = '50%')
br()
br()
actionButton('add', 'Add to library', width = '100%')

get_table <- eventReactive(input$search, {
	withProgress({
		find_oclc(author = input$inAuthor, 
							title = input$inTitle, 
							isbn = input$inISBN) %>%
		full_query_to_df() %>%
	    dplyr::mutate(lyr = as.numeric(as.character(lyr)),
	                  hyr = as.numeric(as.character(lyr))) %>%
			dplyr::mutate(lyr = replace(lyr, is.na(lyr), 1800), 
										hyr = replace(hyr, is.na(hyr), lubridate::year(Sys.Date()))) %>%
	      dplyr::mutate(author = as.character(author),
	                    author = replace(author, is.na(author), "---")) 
	}, message = "Consulting library catalogs")
		
})


output$NA_lcc_message <- renderUI({
	input$inLCC
	if(grepl('NA', input$inLCC)) {
		h6(strong("Warning: "), "I was unable to generate a complete LCC classification number. Before you add it to the collection, replace the 'NA' characters in the classification field, by the library of congress subject number. Use", strong(a("this table", href = "http://www.questionpoint.org/crs/html/help/zs/ask/ask_map_lcctoddc.html", target = "_blank")) ,", the Dewey number, and ", strong(a("this page", href = "https://www.loc.gov/catdir/cpso/lcco/", target = "_blank")), " as a guide.") %>% return()
	}
})

output$duplicated_item <- renderUI({
	if(input$inLCC %in% items()$number){
		h6(strong("Warning: "), "This item is already in the library and the library classification number needs to be unique. You can add a digit to make it different.") %>% return()
	}
})

output$message_max <- renderUI({
	n_obs <- get_table() %>% nrow()
	if(n_obs == 25) {
		h6(strong("Attention: "), "I found quite a lot of entries, try to narrow down the search")
		}
	})

output$book_details <- renderUI({
	if(stringr::str_detect(as.character(get_record()$author), "\\|")){
		pattern <- "^.*?(?=\\|)"
	} else {
		pattern <- ".+"
	}
	list(
		h6(em(as.character(get_record()$title)), "by", 
			 em(stringr::str_extract(as.character(get_record()$author), pattern)),
			 " — ", "Topics: ", as.character(get_record()$fast), 
			 " — ", "Dewey: ", as.character(get_record()$ddc)
			 )
	)
})

output$initial_suggestion <- renderUI({
	if(input$add == 0){
	  list(
	    h6(
	      strong("Attention: "),
	      "Check the",
	      a("instructions", href = "#instructions"),
	      "If it's the first time you add an item or you are unsure how to proceed"
	    )
	  )
	}
})

# renderPrint(is.null(input$full_table_rows_selected))
```


Row {data-height = 350}
-----------------------------------------------------------------------

###

```{r}
renderValueBox(uiOutput("initial_suggestion"))
renderValueBox(uiOutput('NA_lcc_message'))
renderValueBox(uiOutput("duplicated_item"))
renderValueBox(uiOutput('message_max'))
renderValueBox(uiOutput("book_details"))

```


Row {data-height = 650}
-----------------------------------------------------------------------

###

```{r}

DT::dataTableOutput("full_table")

output$full_table <- DT::renderDataTable({
  get_table() %>%
    # dplyr::filter(format != 'eBook',
    # 							format != 'eAudiobook') %>%
    dplyr::select(author, title, format) %>%
    datatable(options = list(
      pageLength = 25, 
      # scroller = TRUE,
      # deferRender = TRUE,
      # scrollY = "50%",
      paging = FALSE,
      binfo = FALSE,
      dom = "t" #,
      # columnDefs = list(list(
      #   targets = c(0,1),
      #   render = JS(
      #     "function(data, type, row, meta) {",
      #     "return type === 'display' && data.length > 111 ?",
      #     # "'<span title=\"' + data + '\">' + data.substr(0, 111) + '...</span>' : data;",
      #     "}")
      # )
      # )
      ),
      rownames = F, 
      selection = 'single', 
      style = "bootstrap", 
      filter = "none", 
      fillContainer = TRUE)
})


get_record <- eventReactive(input$full_table_rows_selected, {
	withProgress({
		this <- get_table() %>%
			# dplyr::filter(format != 'eBook',
			# 							format != 'eAudiobook') %>%
			dplyr::slice(input$full_table_rows_selected)
		this_owi <- this %$% owi 
		
		# download xml data
		o <- find_oclc(owi = this_owi, summary = 'false')
		
		get_table()  %>%
			# dplyr::filter(format != 'eBook',
			# 							format != 'eAudiobook') %>%
			dplyr::slice(input$full_table_rows_selected) %>%
			dplyr::mutate(lcc = gsub("\\..*$", "", get_cc(o)),
										ddc = get_cc(o, 'ddc'),
										isbn = find_xisbn(this_owi), 
										fast = get_fast(o)) %>%
			# dplyr::rowwise() %>%
			dplyr::mutate(cutter_author = substr(get_cutter(author),1, 4),
										cutter_title = substr(get_cutter(title),1, 3))
		
	}, message = 'looking for detailed records')
})


observeEvent(get_record(),{
	updateTextInput(session, 'inTitle', value = as.character(get_record()$title))
	updateTextInput(session, 'inAuthor', value = as.character(get_record()$author))
	updateTextInput(session, 'inISBN', value = as.character(get_record()$isbn))
	updateSelectInput(session, 'inYear',
										choices = as.numeric(as.character(get_record()$lyr)):as.numeric(as.character(get_record()$hyr)),
										selected = as.numeric(as.character(get_record()$lyr)))
	updateTextInput(session, 'inLCC', value = paste(
		as.character(get_record()$lcc), 
		as.character(get_record()$cutter_author),
		as.character(get_record()$cutter_title), sep = "."))
})

observeEvent(input$clear, {
	reset('inTitle') 
	reset('inAuthor') 
	reset('inYear')
	reset('inISBN')
	reset('inLCC') 
})

ready_to_add <- reactive(
	all(
		# !grepl("NA", input$inLCC),
		input$inTitle != '',
		input$inAuthor != '',
		input$inYear != '',
		input$inLCC != '', 
		!(input$inLCC %in% items()$number),
		!grepl('NA', input$inLCC)
		)
)

observe(
	toggleState('add', condition = ready_to_add())
)

observeEvent(input$add, {
	records <- dplyr::src_sqlite(path_to_db, create = TRUE)
	
	if(is.null(input$full_table_rows_selected)){
	  df <- data.frame(author = NA, 
	                   format = "Book",
	                   hyr = NA,
	                   lyr = NA,
	                   owi = NA,
	                   title = NA,
	                   lcc = NA,
	                   ddc = NA,
	                   isbn = NA,
	                   fast = NA,
	                   cutter_author = NA,
	                   cutter_title = NA,
	                   number = NA,
	                   year = NA,
	                   date_added = NA)
	} else {
	  df <- get_record()
	}
	item <-df %>%
			dplyr::mutate(number = input$inLCC,
						 year = input$inYear, 
						 date_added = as.character(Sys.time()),
						 title = input$inTitle,
						 author = input$inAuthor, 
						 isbn = input$inISBN)
	if (length(DBI::dbListTables(records$con))== 0) {
		dplyr::copy_to(records, item, name = "records", temporary = FALSE)
	} else {
		DBI::dbWriteTable(records$con, 'records', item, append = TRUE, row.names = F)
	}
	DBI::dbDisconnect(records$con)
	reset('inTitle') 
	reset('inAuthor') 
	reset('inYear')
	reset('inISBN')
	reset('inLCC') 
	values$update_item_table <- values$update_item_table + 1
})

```

instructions {data-orientation=rows}
=======================================================================

## Column 

### {data-width=800}

<div style="font-weight: lighter;">

Two process are central to managing a library catalog: 1) Each item must have accurate details (author, title, year, [ISBN](https://en.wikipedia.org/wiki/International_Standard_Book_Number), etc) and 2) each item must have an classification number that allows to both uniquely identify the item and to organize the items within appropriate subjects 

This app makes these two processes easier by finding the details of a book and generating the classification number. It achieves it by trying to find the book in the public databases of the [Online Computer Library Center](https://www.oclc.org/home.en.html), and [WorldCat](https://www.worldcat.org/), effectively checking for similar items in more than 72,000 libraries in 170 countries. However sometimes it wont be able to find the book or it's classification number in another library and it's important you understand how it works. 

Currently there are two major universal [classification systems](https://en.wikipedia.org/wiki/Library_classification) in use: the [Dewey Decimal](https://en.wikipedia.org/wiki/Dewey_Decimal_Classification) and [Library of Congress](https://en.wikipedia.org/wiki/Library_of_Congress_Classification) (LCC). Although in small academic libraries Dewey is most commonly used, here we use the Library of Congress Classification system because, as opposed to Dewey, the classification codes are freely available and hence it is easier to generate classification codes for items not previously classified in other libraries.

An LCC classification number is composed of four parts: the subject code, the author code, the title code and optionally the volume or copy id. For example the code for "Advances in marine biology Volume 10" by "Russell, Frederick" is **QH91.R877.A38 V10**. The first letter **QH91** indicates that the subject of the book is Science > natural history/biology > General. **R877** is the author [cutter expansive classification](https://en.wikipedia.org/wiki/Cutter_Expansive_Classification). It  starts with R (for Russell) and continues assigning three digits [which depend on the following letters in the name](http://anjackson.net/zombse/062013%20Libraries%20&%20Information%20Science/static/questions/1034.html). You don't have to know these rules, as the code can be generated using the text box on the right. Then, the title code is **A38** which just as the author code starts with the first letter of the title, A, but then has two digits instead of three. Finally, if the item has several volumes or there are several copies you add that info at the end V10 for Volume 10 and C2 if it were the second copy of the book. If there is just one copy or just one volume, you don't have to add anything.

When you search for an item the app will return the most common classification number used in libraries elsewhere. But the code is not written in stone. The same book can have different numbers in different libraries. For instance a book entitled "The Physiology and Medicine of Diving" could be in the subject RC1005 for "submarine medicine" or GV840 for "water-sports > diving". It is important that when you add a new item, check that the classification number makes the most sense for Aldabra's library.

Sometimes, the app will be able to find the item in other libraries, but it won't be able to find the classification number. In those instances, it will show you the Dewey number which you can use in a [Dewey-LCC conversion table](http://www.questionpoint.org/crs/html/help/zs/ask/ask_map_lcctoddc.html) to find the first two letters of the Library of Congress subject code. Then you can find the category in the [classification outline](https://www.loc.gov/catdir/cpso/lcco/) to find the whole code. Nevertheless sometimes is easier to use the same category as other items you know belong to the same category. 

Sometimes the app won't be able to find the item in other libraries at all. In those cases you have to generate the whole thing. Look in the [classification outline](https://www.loc.gov/catdir/cpso/lcco/) or find books with the same subject and then create the author and title codes using the tool on the right. 

</div>

### Generate author and tittle cutter codes {data-width=200}

```{r cutter}
textInput("text_to_code", "Insert author or title", "aldabra", width = "100%")


renderUI({
  list(
    h5("If author: "), 
    substr(get_cutter(input$text_to_code),1, 4),
    h5 ("If title:"),
    substr(get_cutter(input$text_to_code),1, 3)
  )
})

```

advanced {vertical_layout=scroll}
=======================================================================

Row
-----------------------------------------------------------------------

### 

```{r}

valueBox("Excel", caption = downloadLink("excel_file", "Download a list of all books in the library"), icon = "fa-file-excel-o")

output$excel_file <- downloadHandler(
	filename = function() {
		paste0("Aldabra-library_", Sys.Date(), ".csv")
	}, 
	content = function(file){
		# records <- dplyr::src_sqlite(db_location, create = TRUE)
		# 
		# validate(
		# 	need("records" %in% dplyr::src_tbls(records), "The library has no items. Go ahead and add some :)")
		# )
		# 
		# items <- dplyr::tbl(records, "records") %>%
		# 	dplyr::collect()
		# 
		# DBI::dbDisconnect(records$con)
	  values$update_item_table <-   values$update_item_table + 1

	items() %>%
		# dplyr::mutate(number = paste(lcc, cutter_author, cutter_title, sep = ".")) %>%
		dplyr::rename(topics = fast) %>%
	  dplyr::rowwise() %>%
	  dplyr::mutate(subject = stringr::str_split(number, "\\.")[[1]][1],
	                author_title = paste(
	                  stringr::str_split(number, "\\.")[[1]][2],
	                  stringr::str_split(number, "\\.")[[1]][3], 
	                  sep = ".")) %>%
		dplyr::select(number, author, title, year, isbn, topics, date_added, subject, author_title) %>%
	  dplyr::mutate() %>%
		write.csv(file)	
	}
)

```


### 

```{r}
valueBox("Zotero", downloadLink("zotero_file", "Download a .bib file which can be used to import the library into Zotero"), icon = "fa-book")

output$zotero_file <- downloadHandler(
	filename = function() {
		paste0("Aldabra-library_", Sys.Date(), ".bib")
	}, 
	content = function(file){
			records <- dplyr::src_sqlite(path_to_db, create = TRUE)
	
	validate(
		need("records" %in% dplyr::src_tbls(records), "The library has no items. Go ahead and add some :)")
	)

	items <- dplyr::tbl(records, "records") %>%
		dplyr::collect()
	
	DBI::dbDisconnect(records$con)
	
	items %<>%
		dplyr::mutate(number = paste(lcc, cutter_author, cutter_title, sep = ".")) %>%
		dplyr::rename(topics = fast)
	
	foreach(i=1:nrow(items)) %do%{
		if(items$format[i] == "Thesis/dissertation") {
			items$format[i] <- "PhdThesis"
		} else if(!(items$format[i] %in% c("Book", "Article"))) {
			items$format[i] <- "Misc"
		}
		BibEntry(items$format[i], 
						 title = items$title[i],
						 author = parse_person(items$author[i], "Author"), 
						 date = items$year[i],
						 editor = parse_person(items$author[i], "Editor"), 
						 isbn = items$isbn[i])
	} %>% 
		toBiblatex() %>%
		writeLines(file)
	}
)
```

Row
-----------------------------------------------------------------------


### Location of the database file

**Important** — Only modify this if you know what you are doing. For example if you are re-organizing the files in the server.

```{r}

textInput("dbLocation", "", width = "100%", value = db_location)
actionButton("changeDBlocation", "Update and reload")

observeEvent(input$changeDBlocation, {
	if(file.exists("./path_to_db")){
		file.remove("./path_to_db")
	} 
	file.create("./path_to_db")
	writeLines(input$dbLocation, "./path_to_db")
	session$reload()
})



```


